export const TOGGLE_FAVORITE_IMAGE = "TOGGLE_FAVORITE_IMAGE";
export const SET_FAVORITE_IMAGES = "SET_FAVORITE_IMAGES";
export const REMOVE_FAVORITE_IMAGE = "REMOVE_FAVORITE_IMAGE";
export const UPDATE_FAVORITE_IMAGE = "UPDATE_FAVORITE_IMAGE";
export const ADD_COMMENT_FAVORITE_IMAGES = "ADD_COMMENT_FAVORITE_IMAGES";
export const REMOVE_COMMENT_FAVORITE_IMAGES = "REMOVE_COMMENT_FAVORITE_IMAGES";
export const EDIT_COMMENT_FAVORITE_IMAGES = "EDIT_COMMENT_FAVORITE_IMAGES";
