const types = {
  ADD_IMAGE: "ADD_IMAGE",
  REMOVE_IMAGE: "REMOVE_IMAGE",
  SET_IMAGES: "SET_IMAGES",
  ADD_COMMENT_IMAGES: "ADD_COMMENT_IMAGES",
  REMOVE_COMMENT_IMAGES: "REMOVE_COMMENT_IMAGES",
  EDIT_COMMENT_IMAGES: "EDIT_COMMENT_IMAGES",
  SEARCH_IMAGES: "SEARCH_IMAGES"
};

export default types;
