export const ADD_IMAGE = "ADD_IMAGE";
export const REMOVE_IMAGE = "REMOVE_IMAGE";
export const SET_IMAGES = "SET_IMAGES";
export const ADD_COMMENT_IMAGES = "ADD_COMMENT_IMAGES";
export const REMOVE_COMMENT_IMAGES = "REMOVE_COMMENT_IMAGES";
export const EDIT_COMMENT_IMAGES = "EDIT_COMMENT_IMAGES";
export const SEARCH_IMAGES = "SEARCH_IMAGES";
export const UPDATE_IMAGE = "UPDATE_IMAGE";
